### ISSUE TITLE
hi, about voxels  CutIntoVoxels

### ISSUE THREAD

**Issue by francisliyy** [dbrizov/Unity-WaterBuoyancy#1]
sorry ,i am not sure about what's the voxels, what does it use for , and why do like cutintovoxels,
could you explain something for me ? thanks

**Comment by dbrizov** [comment]
Sorry for the late reply mate.
Voxel is something like a pixel, but in 3D space. You can think of a voxel like a very tiny cube.
I am cutting the colliders into voxels, and I am applying up-force to each one, so that the objects can float.
